let
    Источник = Excel.Workbook(File.Contents("C:\Users\KurzanovAV\Documents\Отчетность перед СД\Структура доходов и расходов.xlsx"), null, true),
    to_BI_Sheet = Источник{[Item="to_BI",Kind="Sheet"]}[Data],
    #"Удаленные столбцы" = Table.RemoveColumns(to_BI_Sheet,{"Column1", "Column2"}),
    #"Транспонированная таблица" = Table.Transpose(#"Удаленные столбцы"),
    #"Повышенные заголовки" = Table.PromoteHeaders(#"Транспонированная таблица", [PromoteAllScalars=true]),
    #"Измененный тип" = Table.TransformColumnTypes(#"Повышенные заголовки",{{"Вид дохода/расхода", type date}, {"Проценты от Банка России", type number}, {"Проценты от ИП", type number}, {"Проценты от МБК", Int64.Type}, {"проценты от ФЛ", type number}, {"Проценты от ЮЛ", type number}, {"Проценты по остаткам на кор.счетах", type number}, {"Размещение средств на брокерских счетах под %", type number}, {"Column9", type number}, {"Доход от продажи", type number}, {"Дивиденды", type number}, {"Комиссионный доход за бланки векселей", Int64.Type}, {"Доверительное управление ", type number}, {"Положительная переоценка", type number}, {"НКД, дисконт", type number}, {"Column16", type number}, {"Доход от купли-продажи инвалюты", type number}, {"Доход от переоценки инвалюты", type number}, {"Доходы по валютному контролю", type number}, {"РКО по счетам в инвалюте", type number}, {"Column21", type number}, {"По расчетным операциям ЮЛ и ИП", type number}, {"По расчетным операциям ФЛ", type number}, {"По кассовым операциям ЮЛ и ИП", type number}, {"По кассовым операциям ФЛ", type number}, {"По приему платежей ФЛ без открытия счета", type number}, {"По кредитным операциям", type number}, {"По платежным системам", type number}, {"СМС-информатор", type number}, {"По прочим операции ЮЛ и ИП", type number}, {"По прочим операциям ФЛ", type number}, {"Прочие доходы", Int64.Type}, {"Column33", type number}, {"Доход от купли-продажи драг.металлов", type number}, {"Доход от операций с иностр.монетами", Int64.Type}, {"За услуги по хранению слитков", type number}, {"Переоценка по драг.металлам", type number}, {"Column38", type number}, {"Интернет-Банк", Int64.Type}, {"Кассовое обслуживание тек.счетов ФЛ", type number}, {"Комиссионный доход от ""visa""", Int64.Type}, {"Комиссионный доход от ""МИР""", type number}, {"Обслуживание зарплатных проектов", type number}, {"По POS-терминалам ", type number}, {"По платежным терминалам", type number}, {"По предоплаченным банковским картам", type number}, {"По программе Патриот", Int64.Type}, {"проект ТРАКТОР", Int64.Type}, {"Расчетное обслуживание тек.счетов ФЛ", type number}, {"Штрафы", Int64.Type}, {"Эквайринг", type number}, {"Прочие доходы_1", type number}, {"Расчетное  обслуживание тек.счетов по корпорат. банк.картам", Int64.Type}, {"СБП", type number}, {"Column55", type number}, {"За кассовое обслуживание кред.орг", Int64.Type}, {"Инкассация", type number}, {"Column58", type number}, {"Доходы от восстановления РВПС", type number}, {"Column60", type number}, {"Доходы от восстановления резервов по прочим активам", type number}, {"Column62", type number}, {"От сдачи в аренду сейфовых ячеек", Int64.Type}, {"Column64", Int64.Type}, {"Сдача имущества в аренду", type number}, {"Column66", type number}, {"Переоценка имущества", type number}, {"Реализация (выбытие) имущества", type number}, {"Column69", type number}, {"Доходы от реализации памятных монет", type number}, {"Column71", type number}, {"Уменьшение обязательств по выплате вознаграждений", type number}, {"Column73", type number}, {"Штрафы по кредитным операциям", type number}, {"Штрафы по прочим операциям", Int64.Type}, {"Column76", type number}, {"Внереализационные доходы", type number}, {"Возврат излишне уплаченных процентов по депозитам", type number}, {"По кредитным операциям_2", type number}, {"Прочие доходы_3", type number}, {"Погашение приобретенных прав требования", type number}, {"Column82", type number}, {"Корректировки МСФО", type number}, {"Column84", type number}, {"Доходы от восстановления резервов по ценным бумагам", type number}, {"Column86", type number}, {"Переоценка имущества_4", type number}, {"Column88", type number}, {"Доходы от восстановления резервов по драгоценным металлам", type number}, {"Column90", type number}, {"Уменьшение налога на прибыль на отложенный налог", type number}, {"Column92", type number}, {"Column93", type number}, {"Проценты по вкладам ФЛ", type number}, {"Проценты по депозитам ЮЛ и ИП", type number}, {"Проценты по расчетным счетам ЮЛ и ИП", type number}, {"Проценты по текущим счетам", type number}, {"Процентный расход по средствам КО", type number}, {"Column99", type number}, {"По расчетным операциям", type number}, {"По платежным системам_5", type number}, {"Посреднические по ипотеке", Int64.Type}, {"Расходы по обеспечению работы в SWIFT", type number}, {"Column104", type number}, {"Расходы от операций по приобретению и реализации", type number}, {"Расходы профучастника", type number}, {"Премии, уменьшающие проценные доходы", type number}, {"Отрицательная переоценка", type number}, {"Column109", type number}, {"Комиссии за проведение операций с валютой", type number}, {"Комиссии по переводам", type number}, {"Прочие комиссии", type number}, {"Расход от купли-продажи инвалюты", type number}, {"Расход от переоценки инвалюты", type number}, {"Column115", type number}, {"Переоценка по драг.металлам_6", type number}, {"Расход от купли-продажи драг.металлов", Int64.Type}, {"Column118", type number}, {"по POS-терминалам", type number}, {"По банковским картам", type number}, {"По банкоматам", type number}, {"По платежным терминалам_7", type number}, {"По предоплаченным банковским картам_8", type number}, {"По программе Патриот_9", type number}, {"Реклама", type number}, {"Услуги информационных систем", type number}, {"Эквайринг_10", type number}, {"За услуги ""Компас Плюс""", type number}, {"Комиссионный расход ""visa""", Int64.Type}, {"Комиссионный расход ""МИР""", type number}, {"Column131", type number}, {"Расходы на охрану по дог. С ООО ""Уралпромохрана""", Int64.Type}, {"Содержание инкассаторских машин", type number}, {"Страхование", type number}, {"Column135", type number}, {"Расходы по созданию РВПС", type number}, {"Column137", type number}, {"По платежным системам_11", Int64.Type}, {"Расходы по созданию резервов по прочим активам", type number}, {"Column140", type number}, {"Заработная плата и отчисление в ФОТ", type number}, {"Аренда", Int64.Type}, {"Вычисл. и оргтехника, кассовое оборудование, прочее оборудование", type number}, {"Амортизация", type number}, {"Канцелярские расходы", type number}, {"Командировочные расходы", type number}, {"Мебель и хозинвентарь", type number}, {"Охрана", Int64.Type}, {"Представительские расходы", type number}, {"Приобретение ПО и лицензий", type number}, {"Прочие расходные материалы, связ. с банк. Деятельностью", type number}, {"Страхование_12", type number}, {"Расходы по подготовке кадров", type number}, {"Расходы по подписке на период. издания", type number}, {"Расходы по установке системы Клиент-Банк", type number}, {"Реклама_13", type number}, {"Ремонт здания", type number}, {"Судебные иски, госпошлина, нотариус", type number}, {"Транспортные расходы", type number}, {"Услуги информационных систем_14", type number}, {"Услуги связи", type number}, {"Тепло/электроэнергия, водоснабжение и содержание зданий", type number}, {"Почтовые услуги", type number}, {"Приобретение спец. одежды и прочие расходы", type number}, {"Оплата за обработку плат.документов", type number}, {"Программное обслуживание (ООО ""Уралпромтех"")", Int64.Type}, {"Амортизация АФПП", type number}, {"Аренда АФПП %%", type number}, {"Аренда АФПП (корректировка)", Int64.Type}, {"прочее", Int64.Type}, {"Column171", type number}, {"Страхование вкладов", type number}, {"Column173", type number}, {"услуги аудиторов", Int64.Type}, {"Column175", Int64.Type}, {"Расход по приобретению футляров для памятных монет", type number}, {"Расход по приобретению альбомов с монетами (оружие победы)", type number}, {"Column178", type number}, {"Штрафы, пени, неустойки", type number}, {"Column180", type number}, {"Увеличение обязательств по выплате вознаграждений", type number}, {"Column182", type number}, {"за раскрытие информации", type number}, {"Материальная помощь", Int64.Type}, {"На благотворительные услуги", type number}, {"Прочие расходы", type number}, {"Расходы от списания активов (кредитов)", Int64.Type}, {"Column188", type number}, {"уплаченные налоги", type number}, {"отложенные налоги", type number}, {"Column191", type number}, {"Переоценка имущества_15", type number}, {"Реализация (выбытие) имущества_16", type number}, {"Содержание имущества", type number}, {"Ремонт  ", Int64.Type}, {"Column196", type number}, {"Расходы по созданию резервов по ценным бумагам", type number}, {"Column198", type number}, {"Корректировки МСФО_17", type number}, {"Column200", type number}, {"Расходы по переоценки основных средств", type number}, {"Column202", type number}, {"Реализация (выбытие) имущества_18", Int64.Type}, {"Column204", Int64.Type}, {"Column205", type number}, {"Column206", type number}}),
    #"Переименованные столбцы" = Table.RenameColumns(#"Измененный тип",{{"Column93", "Всего доходов"}, {"Column205", "Всего расходов"}, {"проценты от ФЛ", "Проценты от ФЛ"}, {"Вид дохода/расхода", "Период"}}),
    #"Удаленные столбцы1" = Table.RemoveColumns(#"Переименованные столбцы",{"Column9", "Column16", "Column21", "Column33", "Column38", "Column55", "Column58", "Column60", "Column62", "Column64", "Column66", "Column69", "Column71", "Column73", "Column76", "Column82", "Column84", "Column86", "Column88", "Column90", "Column92", "Column99", "Column104", "Column109", "Column115", "Column118", "Column131", "Column135", "Column137", "Column140", "Column171", "Column173", "Column175", "Column178", "Column180", "Column182", "Column188", "Column191", "Column196", "Column198", "Column200", "Column202", "Column204", "Column206"}),
    #"Добавлен столбец Проценты по кредитам" = Table.AddColumn(#"Удаленные столбцы1", "Проценты по кредитам", each ([Проценты от ИП] + [Проценты от ФЛ] + [Проценты от ЮЛ]) / 1000),
    #"Добавлен столбец Проценты от размещения свбодных средтв" = Table.AddColumn(#"Добавлен столбец Проценты по кредитам", "Проценты от размещения свбодных средтв", each ([Проценты от Банка России] + [Проценты от МБК] + [Проценты по остаткам на кор.счетах] + [#"Размещение средств на брокерских счетах под %"]) / 1000),
    #"Добавлен столбец Процентные доходы" = Table.AddColumn(#"Добавлен столбец Проценты от размещения свбодных средтв", "Процентные доходы", each ([Проценты от Банка России] + [Проценты от ИП] + [Проценты от МБК] + [Проценты от ФЛ] + [Проценты от ЮЛ] + [Проценты по остаткам на кор.счетах] + [#"Размещение средств на брокерских счетах под %"] + [#"НКД, дисконт"]) / 1000),
    #"Добавлен столбец Добавлен пользовательский объект" = Table.AddColumn(#"Добавлен столбец Процентные доходы", "Доходы по ценным бумагам", each ([Доход от продажи] + [Дивиденды] + [#"Доверительное управление "] + [#"НКД, дисконт"]) / 1000),
    #"Добавлен столбец Процентные расходы" = Table.AddColumn(#"Добавлен столбец Добавлен пользовательский объект", "Процентные расходы", each ([Проценты по вкладам ФЛ] + [Проценты по депозитам ЮЛ и ИП] + [Проценты по расчетным счетам ЮЛ и ИП] + [Проценты по текущим счетам] + [Процентный расход по средствам КО]) * (-1) / 1000),
    #"Добавлен столбец Чистый процентный доход" = Table.AddColumn(#"Добавлен столбец Процентные расходы", "Чистый процентный доход", each [Процентные доходы] - [Процентные расходы]),
    #"Добавлен столбец Финансовый результат" = Table.AddColumn(#"Добавлен столбец Чистый процентный доход", "Финансовый результат", each ([Всего доходов] + [Всего расходов]) / 1000),
    #"Добавлен столбец Доходы по валютным операциям" = Table.AddColumn(#"Добавлен столбец Финансовый результат", "Доходы по валютным операциям", each ([#"Доход от купли-продажи инвалюты"] + [Доходы по валютному контролю] + [РКО по счетам в инвалюте]) / 1000)
in
    #"Добавлен столбец Доходы по валютным операциям"
